# Configuration related to monitoring file changes.
watch:
  # File extensions when watching directories. Shiba recognizes these file extensions as Markdown
  # files and updates its preview when they are modified.
  file_extensions:
    - md
    - mkd
    - markdown
  # Throttle for debouncing file change events in milliseconds. This is useful to avoid the preview
  # repeatedly within very short span. This throttle is necessary since it is very common that text
  # editor modifies the file multiple times on saving.
  debounce_throttle: 50

# Key mappings. Keys are key binds and their values are corresponding actions to be bound. Any
# keymap sequences supported by mousetrap[1] are available for keys. Predefined action names are
# available for values.
#
# [1]: https://craig.is/killing/mice
keymaps:
  j: ScrollDown
  k: ScrollUp
  h: ScrollLeft
  l: ScrollRight
  g: ScrollTop
  G: ScrollBottom
  d: ScrollPageDown
  u: ScrollPageUp
  space: ScrollPageDown
  down: ScrollDown
  up: ScrollUp
  left: ScrollLeft
  right: ScrollRight
  pagedown: ScrollPageDown
  pageup: ScrollPageUp
  ctrl+down: ScrollPageDown
  ctrl+up: ScrollPageUp
  ctrl+shift+down: ScrollBottom
  ctrl+shift+up: ScrollTop
  ctrl+j: ScrollNextSection
  ctrl+k: ScrollPrevSection
  ctrl+b: GoBack
  ctrl+f: GoForward
  ctrl+o: OpenFile
  ctrl+shift+o: OpenDir
  ctrl+h: History
  ctrl+r: Reload
  o: Outline
  s: Search
  plus: ZoomIn
  -: ZoomOut
  ctrl+m: MaximizeWindow
  mod+q: Quit
  ?: Help

# Configuration related to text search.
search:
  # How search query matches to text. The following preset matchers are available. Note that matcher
  # can be changed by clicking an icon in the search box.
  #
  # - SmartCase: case-sensitive when some upper case alphabets are included. Otherwise case-insensitive
  # - CaseSensitive: always case-sensitive
  # - CaseInsensitive: always case-insensitive
  # - CaseSensitiveRegex: case-sensitive regular expression
  matcher: SmartCase

# Configuration related to application window.
window:
  # Remember the window state (position, size, ...) and restore it when opening Shiba at next time.
  restore: false
  # Theme to apply to the application window. The following predefined values are available.
  #
  # - System: use theme set to the system settings
  # - Dark: always use dark theme
  # - Light: always use light theme
  theme: System
  # Application window is always on top of other windows.
  always_on_top: false
  # Default window size (width and height) in logical pixels or "max" to maximize the window in the
  # specified direction. For example, the following configuration creates a window with a maximized
  # height and a width of 800px.
  #
  # ```
  # default_size:
  #   width: 800
  #   height: max
  # ```
  #
  # For another example, the following configuration maximizes the window in the both directions.
  #
  # ```
  # default_size:
  #   width: max
  #   height: max
  # ```
  #
  # When `restore` is set to `true` and a saved window state exists, the window size from the saved
  # state is used.
  default_size:
    width: 600
    height: 800
  # Setting `true` shows a menu bar at the top of application window. Setting `false` hides the menu
  # bar. This configuration is effective only on Linux and Windows. On macOS, the menu bar is always
  # set.
  menu_bar: false
  # Setting `true` enables platform-specific vibrant effects on the window.
  # On macOS it uses `NSVisualEffectView`[1]. On Windows it uses Mica material[2]. It is available
  # on Windows 11 or later. On Linux this option has no effect.
  # When `false` is set, Shiba uses solid background colors. It may slightly improve the performance
  # of the application rendering and launch.
  #
  # [1]: https://developer.apple.com/design/human-interface-guidelines/materials
  # [2]: https://learn.microsoft.com/en-us/windows/apps/design/style/mica
  vibrant: true

# Configuration related to Markdown preview content.
preview:
  # Highlight theme for code blocks. Themes provided by highlight.js are available. For example, the
  # following configuration uses 'Mono Blue' in light mode, and uses 'Tokyo Night Dark' in dark mode.
  #
  # ```
  # highlight:
  #   light: Mono Blue
  #   dark: Tokyo Night Dark
  # ```
  #
  # See the demo page to know all highlight themes: https://highlightjs.org/static/demo/
  highlight:
    light: GitHub
    dark: GitHub Dark
  # Override CSS styles applied to Markdown preview with specified CSS file path. The path is
  # relative to the configuration directory.
  # Notes:
  # - all styles must be applied under the `<article class="markdown-body">` element. Otherwise
  #   they breaks some UI in the application.
  # - fetching external resources (e.g. fonts) is not allowed for security reason at this point
  #
  # For example, when you want to apply dimmed version of GitHub color theme,
  #
  # 1. Download `dark_dimmed.css`[1], dimmed version of GitHub Markdown CSS
  # 2. Put the downloaded file in the configuration directory
  # 3. Set `css: dark_dimmed.css` below
  #
  # [1]: https://github.com/hyrious/github-markdown-css
  css: null
  # Maximum number of files to remember as history. The history is remembered persistently and can be
  # referred via 'History' menu item or keyboard shortcut.
  history_size: 100

# Configuration related to dialog to open a file or watch a directory.
dialog:
  # Default directory path to open when selecting a file to preview or a directory to watch. The
  # following example opens `~/Documents` by default. When `null` is specified, OS will determine
  # the default directory.
  #
  # ```
  # default_dir: ~/Documents
  # ```
  default_dir: null
